### ISSUE TITLE
--edit_config_json 参数无法成功把boolean类型的参数改成false

### ISSUE THREAD

**Issue by yangxudong** [alibaba/EasyRec#155]
如下配置无法成功，因为代码内部先把配置项的值 改成了string，即 'fasle', 然后再强制类型转换为bool

--edit_config_json={\\"export_config.multi_placeholder\\":false}

在python中   bool('false') = True

boolean类型的参数需要特别处理。

**Comment by chengmengli06** [comment]
fixed
