### ISSUE TITLE
eval_config 里加 gauc，报错 TypeError: Can't convert Operation 'PyFunc' to Tensor

### ISSUE THREAD

**Issue by qingqinggu** [alibaba/EasyRec#161]
训练 DeepFM 模型时，配置文件中的 eval_config 加 gauc，logview 报错：
TypeError: Can't convert Operation 'PyFunc' to Tensor (target dtype=None, name=u'values', as_ref=False)
Failed to execute system command. (exit code: 251.)

具体配置如下：
eval_config {
  metrics_set: {
    gauc {
      uid_field: "uid"
    }
  }
  eval_online: true
}

**Comment by chengmengli06** [comment]
![image](https://user-images.githubusercontent.com/31561586/164383230-a156d29f-e659-4cc9-8848-5afdb91400d7.png)
