### ISSUE TITLE
eval_config 里加 max_f1，报错 Can't convert Operation 'group_deps' to Tensor

### ISSUE THREAD

**Issue by qingqinggu** [alibaba/EasyRec#162]
训练 DeepFM 模型时，配置文件中的 eval_config 加 max_f1，logview 报错：
TypeError: Can't convert Operation 'group_deps' to Tensor (target dtype=None, name=u'values', as_ref=False)
Failed to execute system command. (exit code: 251.)

具体配置如下：
eval_config {
metrics_set: {
max_f1 {}
}
eval_online: true
}

**Comment by chengmengli06** [comment]
fixed.
