### ISSUE TITLE
pai command '-Dtrain_tables=odps://XXX' not support partition like 'BETWEEN XXX AND XXX' 

### ISSUE THREAD

**Issue by qingqinggu** [alibaba/EasyRec#173]
PAI command such as "-Dtrain_tables=odps://xxx/tables/xxx/day=${p_day1}" in ODPS SQL not support partition input like 'BETWEEN XXX AND XXX', which is not convenient when few months are needed.
For example:
WHERE day BETWEEN '20220101' AND '20220425';

**Comment by chengmengli06** [comment]
Currently, we are not going to support this feature. Because reading from multiple partitions will result in bad performance, many parameters must be tuned specifically. It is suggested to merge the partitions into one big train table.
