### ISSUE TITLE
How to get negative_sampler file?

### ISSUE THREAD

**Issue by kinghuin** [alibaba/EasyRec#195]
Hi, I have found the link in [here](https://github.com/alibaba/EasyRec/blob/master/docs/source/models/dssm_neg_sampler.md?plain=1#L94) is unavailable. I am so confused about how to get [negative_sampler file](https://github.com/alibaba/EasyRec/blob/master/samples/model_config/dssm_neg_sampler_v2_on_taobao.config#L132). Could you please offer more details about negative_sampler file?

**Comment by kinghuin** [comment]
Hi, I have found the link in [here](https://github.com/alibaba/EasyRec/blob/master/docs/source/models/dssm_neg_sampler.md?plain=1#L94)
is unavailable. I am so confused about how to get [negative_sampler file](https://github.com/alibaba/EasyRec/blob/master/samples/model_config/dssm_neg_sampler_v2_on_taobao.config#L132). Could you please offer more details about negative_sampler file?

**Comment by chengmengli06** [comment]
The document is here: https://easyrec.readthedocs.io/en/latest/models/dssm_neg_sampler.html#id3

**Comment by kinghuin** [comment]
Thanks. But I still not sure the means of the schema, could you give a simple demo for [negative_sampler file](https://github.com/alibaba/EasyRec/blob/master/samples/model_config/dssm_neg_sampler_v2_on_taobao.config#L132)?

**Comment by paradiseHIT** [comment]
https://easyrec.readthedocs.io/en/latest/models/dssm_neg_sampler.html @kinghuin maybe this will help you, you can join DingDing Group: 32260796.

**Comment by kinghuin** [comment]
Thanks for reply :)
