### ISSUE TITLE
Does Dropoutnet dataset only need positive samples?

### ISSUE THREAD

**Issue by kinghuin** [alibaba/EasyRec#196]
Hello, the [dssm document](https://github.com/alibaba/EasyRec/blob/master/docs/source/models/dssm_neg_sampler.md?plain=1#L14) said 

> 注：训练样本一般只需准备点击（正样本）的样本即可

which is no shown in [dropout document](https://github.com/alibaba/EasyRec/blob/master/docs/source/models/dropoutnet.md). 

Does Dropoutnet dataset only need positive samples, just like [dssm_neg_sampler](https://github.com/alibaba/EasyRec/blob/master/docs/source/models/dssm_neg_sampler.md)?
I have tried to use only positive samples to train Dropoutnet  but the result is so poor, which makes me suspicious.

**Comment by chengmengli06** [comment]
both positive and negative are necessary, it does not use negative sampled negatives.
