### ISSUE TITLE
有支持读取TF RECORDS的计划么？

### ISSUE THREAD

**Issue by BigFishDreamWater** [alibaba/EasyRec#206]
本地模式只支持csv.没有看到有读取tf records的接口

**Comment by chengmengli06** [comment]
https://github.com/alibaba/EasyRec/blob/master/easy_rec/python/input/batch_tfrecord_input.py 这个可以吗

**Comment by fooSynaptic** [comment]
> https://github.com/alibaba/EasyRec/blob/master/easy_rec/python/input/batch_tfrecord_input.py 这个可以吗

文档上好像没有找到示例代码
