### ISSUE TITLE
怎麽使用EasyRec?

### ISSUE THREAD

**Issue by zhuozhang090807** [alibaba/EasyRec#208]
我看到EasyRec的代码文件，是用python语言开发的吗？其它语言开发的web站点，可以用这个做推荐系统吗？怎麽使用呢？

**Comment by yunkchen** [comment]
@zhuozhang090807 EasyRec主要用来训练推荐模型，和推荐的业务场景（例如 web站点）实现的语言没有关系；
如果要搭建一套完整的推荐系统，除了模型部分，数据链路的工程也必不可少，以下的实践案例可以借鉴一下：
https://bp.aliyun.com/detail/140?spm=a2cls.b8387508.0.0.4a144a21pxBYVS

**Comment by zhuozhang090807** [comment]
> @zhuozhang090807 EasyRec主要用来训练推荐模型，和推荐的业务场景（例如 web站点）实现的语言没有关系； 如果要搭建一套完整的推荐系统，除了模型部分，数据链路的工程也必不可少，以下的实践案例可以借鉴一下： https://bp.aliyun.com/detail/140?spm=a2cls.b8387508.0.0.4a144a21pxBYVS

谢谢你的及时回复，实践案例收到了，因为我最近在研究推荐系统方面的知识，看到了EasyRec，但是不知道从哪方面入手把它运用到我的系统中，谢谢你发给我的案例。
