### ISSUE TITLE
是否能出一篇wiki讲述如何搭建开发环境？

### ISSUE THREAD

**Issue by GH1995** [alibaba/EasyRec#239]
目前已有的 wiki 过于简陋，也无法跑通单测 https://easyrec.readthedocs.io/en/latest/develop.html

希望能封装 docker 开发环境，详细写一篇文章讲讲怎么用。

**Comment by chengmengli06** [comment]
准备中

**Comment by chengmengli06** [comment]
跑不通单测是遇到什么问题了？

**Comment by chengmengli06** [comment]
Docker开发环境已经ready: https://easyrec.readthedocs.io/en/latest/pycharm_vscode_docker.html

**Comment by GH1995** [comment]
> Docker开发环境已经ready: https://easyrec.readthedocs.io/en/latest/pycharm_vscode_docker.html

该文档过于简陋，未讲清如何搭建开发环境
