### ISSUE TITLE
docker 开发环境搭建失败

### ISSUE THREAD

**Issue by GH1995** [alibaba/EasyRec#242]
我用的 docker 链接是 https://hub.docker.com/repository/docker/gh1995/easyrec-dev ，基于 mybigpai-registry.cn-beijing.cr.aliyuncs.com/easyrec/easyrec:py36-tf1.15-0.4.7，具体命令如下

```
# 创建容器
docker run -itd --name easyrec -p 10022:22 -p 10023:10023 -v ${PWD}:/app/ gh1995/easyrec-dev:latest bash
# 进入容器
docker exec -it easyrec bash
cd /root
# 创建空文件
mkdir .ssh
touch /root/.ssh/authorized_keys
# 设置文件权限
chmod 644 /root/.ssh/authorized_keys
# 复制公钥
cp ~/.ssh/id_rsa.pub /app
cd /app
cat /app/id_rsa.pub >> /root/.ssh/authorized_keys
```
此外，我还做了如下设置
```
将
PasswordAuthentication yes
改为
PasswordAuthentication no

如果行首有#号，将#号去掉

新增一行：
PermitRootLogin prohibit-password
```

```
/etc/init.d/ssh restart
```

在容器外ssh连接正常，但是无法用 PyCharm 上传代码，vs code 也存在同样的问题

<img width="932" alt="image" src="https://user-images.githubusercontent.com/11362493/179460940-9050184e-7e25-4f73-8d53-dba581ef1460.png">
<img width="832" alt="image" src="https://user-images.githubusercontent.com/11362493/179461012-01faa53e-6a64-4c9f-86c7-1148c26a4722.png">
<img width="831" alt="image" src="https://user-images.githubusercontent.com/11362493/179461091-41b9cbf4-a1e4-462b-b266-1e781fe6e4be.png">

**Comment by chengmengli06** [comment]
update /etc/bash.bashrc to remove the tensorflow prompt, which prevents sftp to parse ssh messages correctly:
![image](https://user-images.githubusercontent.com/31561586/192702922-7611e8cd-53f2-4cf5-846b-3c4b9c38d011.png)

**Comment by GH1995** [comment]
> update /etc/bash.bashrc to remove the tensorflow prompt, which prevents sftp to parse ssh messages correctly: ![image](https://user-images.githubusercontent.com/31561586/192702922-7611e8cd-53f2-4cf5-846b-3c4b9c38d011.png)

未能解决问题
