### ISSUE TITLE
dssm负采样模型训练时graph learn读取oss失败

### ISSUE THREAD

**Issue by agentai** [alibaba/EasyRec#291]
请教下，在pai上运行dssm负采样版本时，遇到graph learn读取oss失败的问题，如何解决呢
`[0;31mE0926 20:16:15.558261   142 slice_reader.h:60] Unimplemented:OSS not support GetRecordCount
[m[0;31mE0926 20:16:15.562287   142 edge_loader.cc:98] Try to read next edge file failed, Unimplemented:OSS not support GetRecordCount`

**Comment by chengmengli06** [comment]
Currently graph learn could not read directly from oss, but you can mount oss to a local folder if you are using  DataScience or DLC platforms.
