### ISSUE TITLE
下载train_2gpu.sh 返回403Forbidden

### ISSUE THREAD

**Issue by pilotshuk** [alibaba/EasyRec#316]
根据Local Tutorial 执行wget https://easyrec.oss-cn-beijing.aliyuncs.com/scripts/train_2gpu.sh 返回403Forbidden

**Comment by chengmengli06** [comment]
Here is what you want:  
https://github.com/alibaba/EasyRec/blob/master/scripts/train_2gpu.sh 
https://github.com/alibaba/EasyRec/blob/master/scripts/train_ps.sh
