### ISSUE TITLE
怎么下载EasyRec仓库得这些数据

### ISSUE THREAD

**Issue by xia-huang-411303** [alibaba/EasyRec#32]
![image](https://user-images.githubusercontent.com/30041175/135016810-329ac6b9-49d0-4f65-886b-84335b19ee7e.png)
运行 CUDA_VISIBLE_DEVICES=0 python -m easy_rec.python.train_eval --pipeline_config_path custom_config/dssm_hard_neg_sampler_on_taobao.config这样得命令，发现数据下载不下来

**Comment by xia-huang-411303** [comment]
先wget https://easyrec.oss-cn-beijing.aliyuncs.com/data/easyrec_data_20210818.tar.gz

**Comment by xia-huang-411303** [comment]
资源不存在了, 找管理员

**Comment by chengmengli06** [comment]
now we could use: python git-lfs/git_lfs.py pull
