### ISSUE TITLE
tf searving部署完成后怎么调用推荐服务

### ISSUE THREAD

**Issue by hkjdy** [alibaba/EasyRec#340]
我使用tf searving+docker将EasyRec部署完成后，我要怎么通过API调用推荐服务，没有找到相关文档，请帮忙解答，谢谢！

**Comment by paradiseHIT** [comment]
如果是标准的tf serving，可以调用标准的tf serving即可
可以参考这篇文章
https://easyrec.readthedocs.io/en/latest/predict/%E5%9C%A8%E7%BA%BF%E9%A2%84%E6%B5%8B.html

如果是纯TF Serving，调用参考下面示例
``` shell
# Query the model using the predict API
curl -d '{"instances": [1.0, 2.0, 5.0]}' \
    -X POST http://localhost:8501/v1/models/half_plus_two:predict

```
