### ISSUE TITLE
local安装出错，是否有详细的安装文档？

### ISSUE THREAD

**Issue by kpvt001** [alibaba/EasyRec#345]
➜  EasyRec git:(master) sh scripts/init.sh 
[ERROR] 2023-02-14 16:15:21,918 git_lfs.py[22] : please install python_oss from https://github.com/aliyun/aliyun-oss-python-sdk.git

➜  EasyRec git:(master) pip3 install oss2
出现以下错误：
`    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-zy_rc1oo/cryptography/setup.py", line 18, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-zy_rc1oo/cryptography/`

**Comment by paradiseHIT** [comment]
需要linux系统，我们一般使用centos或者Ubuntu

**Comment by kpvt001** [comment]
> 需要linux系统，我们一般使用centos或者Ubuntu

@paradiseHIT 你好，是在centos上报的错误。

**Comment by yunkchen** [comment]
https://github.com/MISP/misp-docker/issues/113#issuecomment-965016166
试试先更新pip，然后pip install setuptools_rust

**Comment by kpvt001** [comment]
> 

ubuntu 18.04
docer 20.10.7
执行build_docker.sh出错。

目前发现文档上的easyrec的安装会出现各种问题，有计划完善文档吗？

**Comment by kpvt001** [comment]
> [MISP/misp-docker#113 (comment)](https://github.com/MISP/misp-docker/issues/113#issuecomment-965016166) 试试先更新pip，然后pip install setuptools_rust

问题依旧。
先执行过`pip3 install --upgrade pip`、`pip3 install setuptools_rust`后，执行`bash -x scripts/init.sh`，提示

> [ERROR] 2023-02-15 17:06:44,309 git_lfs.py[22] : please install python_oss from https://github.com/aliyun/aliyun-oss-python-sdk.git

在根据`https://github.com/aliyun/aliyun-oss-python-sdk.git`的文档通过`pip3 install oss2`安装后，执行`bash -x scripts/init.sh`，依然提示

> [ERROR] 2023-02-15 17:09:59,361 git_lfs.py[22] : please install python_oss from https://github.com/aliyun/aliyun-oss-python-sdk.gi

**Comment by kpvt001** [comment]
也未能发现文档上提到的` remote - containers` vscode 插件

**Comment by yunkchen** [comment]
> > [MISP/misp-docker#113 (comment)](https://github.com/MISP/misp-docker/issues/113#issuecomment-965016166) 试试先更新pip，然后pip install setuptools_rust
> 
> 问题依旧。 先执行过`pip3 install --upgrade pip`、`pip3 install setuptools_rust`后，执行`bash -x scripts/init.sh`，提示
> 
> > [ERROR] 2023-02-15 17:06:44,309 git_lfs.py[22] : please install python_oss from https://github.com/aliyun/aliyun-oss-python-sdk.git
> 
> 在根据`https://github.com/aliyun/aliyun-oss-python-sdk.git`的文档通过`pip3 install oss2`安装后，执行`bash -x scripts/init.sh`，依然提示
> 
> > [ERROR] 2023-02-15 17:09:59,361 git_lfs.py[22] : please install python_oss from https://github.com/aliyun/aliyun-oss-python-sdk.gi

pip install oss2

**Comment by kpvt001** [comment]
> > > [MISP/misp-docker#113 (comment)](https://github.com/MISP/misp-docker/issues/113#issuecomment-965016166) 试试先更新pip，然后pip install setuptools_rust
> > 
> > 
> > 问题依旧。 先执行过`pip3 install --upgrade pip`、`pip3 install setuptools_rust`后，执行`bash -x scripts/init.sh`，提示
> > > [ERROR] 2023-02-15 17:06:44,309 git_lfs.py[22] : please install python_oss from https://github.com/aliyun/aliyun-oss-python-sdk.git
> > 
> > 
> > 在根据`https://github.com/aliyun/aliyun-oss-python-sdk.git`的文档通过`pip3 install oss2`安装后，执行`bash -x scripts/init.sh`，依然提示
> > > [ERROR] 2023-02-15 17:09:59,361 git_lfs.py[22] : please install python_oss from https://github.com/aliyun/aliyun-oss-python-sdk.gi
> 
> pip install oss2 有安装成功么？import oss2试试

`pip3 install oss2`安装成功

`import oss2`可以找到包，但会出现错误。

> # python3
Python 3.6.9 (default, Jun 29 2022, 11:45:57)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import oss2
/usr/lib/python3/dist-packages/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography (40.0) will be the last to support Python 3.6.
  from cryptography import x509
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/oss2/__init__.py", line 15, in <module>
    from .resumable import resumable_upload, resumable_download, ResumableStore, ResumableDownloadStore, determine_part_size
  File "/usr/local/lib/python3.6/dist-packages/oss2/resumable.py", line 19, in <module>
    from .crypto_bucket import CryptoBucket
  File "/usr/local/lib/python3.6/dist-packages/oss2/crypto_bucket.py", line 10, in <module>
    from .crypto import BaseCryptoProvider
  File "/usr/local/lib/python3.6/dist-packages/oss2/crypto.py", line 21, in <module>
    from aliyunsdkcore import client
  File "/usr/local/lib/python3.6/dist-packages/aliyunsdkcore/client.py", line 32, in <module>
    from aliyunsdkcore.vendored.requests import codes
  File "/usr/local/lib/python3.6/dist-packages/aliyunsdkcore/vendored/requests/__init__.py", line 48, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python3.6/dist-packages/aliyunsdkcore/vendored/requests/packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1550, in <module>
    class X509StoreFlags(object):
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1570, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

**Comment by kpvt001** [comment]
> > > > > [MISP/misp-docker#113 (comment)](https://github.com/MISP/misp-docker/issues/113#issuecomment-965016166) 试试先更新pip，然后pip install setuptools_rust
> > > > 
> > > > 
> > > > 问题依旧。 先执行过`pip3 install --upgrade pip`、`pip3 install setuptools_rust`后，执行`bash -x scripts/init.sh`，提示
> > > > > [ERROR] 2023-02-15 17:06:44,309 git_lfs.py[22] : please install python_oss from https://github.com/aliyun/aliyun-oss-python-sdk.git
> > > > 
> > > > 
> > > > 在根据`https://github.com/aliyun/aliyun-oss-python-sdk.git`的文档通过`pip3 install oss2`安装后，执行`bash -x scripts/init.sh`，依然提示
> > > > > [ERROR] 2023-02-15 17:09:59,361 git_lfs.py[22] : please install python_oss from https://github.com/aliyun/aliyun-oss-python-sdk.gi
> > > 
> > > 
> > > pip install oss2 有安装成功么？import oss2试试
> > 
> > 
> > `pip3 install oss2`安装成功
> > `import oss2`可以找到包，但会出现错误。
> > > # python3
> > 
> > 
> > Python 3.6.9 (default, Jun 29 2022, 11:45:57) [GCC 8.4.0] on linux Type "help", "copyright", "credits" or "license" for more information.
> > > > > import oss2
> > > > > /usr/lib/python3/dist-packages/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography (40.0) will be the last to support Python 3.6.
> > > > > from cryptography import x509
> > > > > Traceback (most recent call last):
> > > > > File "", line 1, in
> > > > > File "/usr/local/lib/python3.6/dist-packages/oss2/**init**.py", line 15, in
> > > > > from .resumable import resumable_upload, resumable_download, ResumableStore, ResumableDownloadStore, determine_part_size
> > > > > File "/usr/local/lib/python3.6/dist-packages/oss2/resumable.py", line 19, in
> > > > > from .crypto_bucket import CryptoBucket
> > > > > File "/usr/local/lib/python3.6/dist-packages/oss2/crypto_bucket.py", line 10, in
> > > > > from .crypto import BaseCryptoProvider
> > > > > File "/usr/local/lib/python3.6/dist-packages/oss2/crypto.py", line 21, in
> > > > > from aliyunsdkcore import client
> > > > > File "/usr/local/lib/python3.6/dist-packages/aliyunsdkcore/client.py", line 32, in
> > > > > from aliyunsdkcore.vendored.requests import codes
> > > > > File "/usr/local/lib/python3.6/dist-packages/aliyunsdkcore/vendored/requests/**init**.py", line 48, in
> > > > > from .packages.urllib3.contrib import pyopenssl
> > > > > File "/usr/local/lib/python3.6/dist-packages/aliyunsdkcore/vendored/requests/packages/urllib3/contrib/pyopenssl.py", line 46, in
> > > > > import OpenSSL.SSL
> > > > > File "/usr/lib/python3/dist-packages/OpenSSL/**init**.py", line 8, in
> > > > > from OpenSSL import crypto, SSL
> > > > > File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1550, in
> > > > > class X509StoreFlags(object):
> > > > > File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1570, in X509StoreFlags
> > > > > CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
> > > > > AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
> 
> OpenSSL的版本问题，可以google下，卸载当前的OpenSSL，安装一个匹配的版本

请问是否能够完善下文档呀。遇到一个问题就在issue里问，这样可能不太方便

**Comment by yunkchen** [comment]
> > > > > > [MISP/misp-docker#113 (comment)](https://github.com/MISP/misp-docker/issues/113#issuecomment-965016166) 试试先更新pip，然后pip install setuptools_rust
> > > > > 
> > > > > 
> > > > > 问题依旧。 先执行过`pip3 install --upgrade pip`、`pip3 install setuptools_rust`后，执行`bash -x scripts/init.sh`，提示
> > > > > > [ERROR] 2023-02-15 17:06:44,309 git_lfs.py[22] : please install python_oss from https://github.com/aliyun/aliyun-oss-python-sdk.git
> > > > > 
> > > > > 
> > > > > 在根据`https://github.com/aliyun/aliyun-oss-python-sdk.git`的文档通过`pip3 install oss2`安装后，执行`bash -x scripts/init.sh`，依然提示
> > > > > > [ERROR] 2023-02-15 17:09:59,361 git_lfs.py[22] : please install python_oss from https://github.com/aliyun/aliyun-oss-python-sdk.gi
> > > > 
> > > > 
> > > > pip install oss2 有安装成功么？import oss2试试
> > > 
> > > 
> > > `pip3 install oss2`安装成功
> > > `import oss2`可以找到包，但会出现错误。
> > > > # python3
> > > 
> > > 
> > > Python 3.6.9 (default, Jun 29 2022, 11:45:57) [GCC 8.4.0] on linux Type "help", "copyright", "credits" or "license" for more information.
> > > > > > import oss2
> > > > > > /usr/lib/python3/dist-packages/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography (40.0) will be the last to support Python 3.6.
> > > > > > from cryptography import x509
> > > > > > Traceback (most recent call last):
> > > > > > File "", line 1, in
> > > > > > File "/usr/local/lib/python3.6/dist-packages/oss2/**init**.py", line 15, in
> > > > > > from .resumable import resumable_upload, resumable_download, ResumableStore, ResumableDownloadStore, determine_part_size
> > > > > > File "/usr/local/lib/python3.6/dist-packages/oss2/resumable.py", line 19, in
> > > > > > from .crypto_bucket import CryptoBucket
> > > > > > File "/usr/local/lib/python3.6/dist-packages/oss2/crypto_bucket.py", line 10, in
> > > > > > from .crypto import BaseCryptoProvider
> > > > > > File "/usr/local/lib/python3.6/dist-packages/oss2/crypto.py", line 21, in
> > > > > > from aliyunsdkcore import client
> > > > > > File "/usr/local/lib/python3.6/dist-packages/aliyunsdkcore/client.py", line 32, in
> > > > > > from aliyunsdkcore.vendored.requests import codes
> > > > > > File "/usr/local/lib/python3.6/dist-packages/aliyunsdkcore/vendored/requests/**init**.py", line 48, in
> > > > > > from .packages.urllib3.contrib import pyopenssl
> > > > > > File "/usr/local/lib/python3.6/dist-packages/aliyunsdkcore/vendored/requests/packages/urllib3/contrib/pyopenssl.py", line 46, in
> > > > > > import OpenSSL.SSL
> > > > > > File "/usr/lib/python3/dist-packages/OpenSSL/**init**.py", line 8, in
> > > > > > from OpenSSL import crypto, SSL
> > > > > > File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1550, in
> > > > > > class X509StoreFlags(object):
> > > > > > File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1570, in X509StoreFlags
> > > > > > CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
> > > > > > AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
> > 
> > 
> > OpenSSL的版本问题，可以google下，卸载当前的OpenSSL，安装一个匹配的版本
> 
> esayrec的提示是先安装oss2，可是oss2已经安装了，easyrec的提示应该跟openssl的关系不大。因为是本地开发和运行，不使用oss，不需要解决oss的问题。 请问是否能够完善下文档呀。遇到一个问题就在issue里问，这样可能不太方便

确实不使用oss2也不影响，但是openssl库影响挺多方面，可以试着跑一下pip install --upgrade pip命令，应该也会报上面的错误；文档我们会更新～

**Comment by yunkchen** [comment]
另外可以加我们钉钉群沟通：32260796
