### ISSUE TITLE
local安装报错

### ISSUE THREAD

**Issue by bingo789** [alibaba/EasyRec#347]
环境：macos，tesorflow2.2
报错信息：
Searching for types-toml
Reading http://mirrors.aliyun.com/pypi/simple/types-toml/
Downloading http://mirrors.aliyun.com/pypi/packages/51/76/fb02b8c63f998a77c576158af89c13b189015766295126a1446f8844c430/types_toml-0.10.8.4-py3-none-any.whl#sha256=306b1bb8b5bbc5f1b60387dbcc4b489e79f8490ce20e93af5f422a68b470d94b
error: sha256 validation failed for types_toml-0.10.8.4-py3-none-any.whl; possible download problem?

**Comment by yunkchen** [comment]
执行哪一步报这个错误？

**Comment by bingo789** [comment]
python setup.py install

解决了。先安装pip install types_toml，估计是网络原因
