### ISSUE TITLE
多目标模型有没有样本数据啊？

### ISSUE THREAD

**Issue by ucas010** [alibaba/EasyRec#353]
hi，dear大佬
多目标模型有没有训练用的数据样本啊？少点也行的。
分享点呗，我测试下。
ESMM用的。

**Comment by yunkchen** [comment]
执行初始化脚本后，data目录下会下载好这些需要的数据～

**Comment by yunkchen** [comment]
我看到已经在钉钉群得到解答了，这边先close了

**Comment by ucas010** [comment]
thx
