### ISSUE TITLE
版本兼容性

### ISSUE THREAD

**Issue by ghost** [alibaba/EasyRec#354]
安装时经常和现有库冲突，建议将v0.6.0（包括后续版本）测试过兼容性的tensorflow、torch版本列在文档里。

**Comment by yunkchen** [comment]
README中有提到当前支持 TF1.12-1.15 / TF2.x

**Comment by flowhs** [comment]
> README中有提到当前支持 TF1.12-1.15 / TF2.x

TF2.x版本范围太广了，比如TF2.5.1在安装时就存在不兼容的包报错

**Comment by yunkchen** [comment]
> 

可以贴一下报错信息么？

**Comment by flowhs** [comment]
> > 
> 
> 可以贴一下报错信息么？

没有保留报错信息，大致是numpy版本冲突。你们在开发v0.6.0时用的tensorflow是哪个版本？

**Comment by chengmengli06** [comment]
2.13之前的都支持，2.13支持中

**Comment by chengmengli06** [comment]
tf 2.13 is ok now
