### ISSUE TITLE
AttributeError: module 'tensorflow._api.v1.data' has no attribute 'TableRecordDataset'

### ISSUE THREAD

**Issue by ucas010** [alibaba/EasyRec#355]
dssm能用，
esmm不能用。
easy-rec                 0.6.1
easyrec                  0.1.0b0
tensorboard              1.15.0
tensorflow-estimator     1.15.1
tensorflow-gpu           1.15.3

**Comment by ucas010** [comment]
from easy_rec.python.protos.dataset_pb2 import DatasetConfig
ModuleNotFoundError: No module named 'easy_rec.python.protos.dataset_pb2'

**Comment by ucas010** [comment]
ESSM
  from easy_rec.python.protos.dataset_pb2 import DatasetConfig
ModuleNotFoundError: No module named 'easy_rec.python.protos.dataset_pb2'

**Comment by yunkchen** [comment]
确认下config中的input_type字段，是不是因为在local跑odps输入模式导致这个报错

**Comment by ucas010** [comment]
已经解决，感谢，will close
