### ISSUE TITLE
dnn使用序列特征怎么设置序列长度

### ISSUE THREAD

**Issue by arccos2002** [alibaba/EasyRec#404]
1.dnn使用序列特征怎么设置序列长度，在序列特征里尝试了配置  max_seq_len和sequence_length，均位生效。
2.max_seq_len和sequence_length什么区别？

**Comment by yangxudong** [comment]
max_seq_len是会生效的，序列的长度会被截断到这个最大长度；并没有sequence_length这个配置项，所以不能配置sequence_length

> 1.dnn使用序列特征怎么设置序列长度，在序列特征里尝试了配置 max_seq_len和sequence_length，均位生效。 2.max_seq_len和sequence_length什么区别？
